# Generated by Django 5.2.17 on 2026-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_procurementrequest_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='department',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Legal & Compliance', 'Legal & Compliance'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Product', 'Product'), ('Sales', 'Sales'), ('Facilities', 'Facilities'), ('Procurement', 'Procurement'), ('Other', 'Other')], max_length=150),
        ),
    ]
